'use strict'

// eslint@6.8.0

module.exports = {
	root: true,
	extends: 'eslint:recommended',
	parserOptions: {
		ecmaVersion: 2020,
		sourceType: 'module'
	},
	env: {
		browser: true,
		node: true,
		commonjs: true,
		shared-node-browser: true
	},
	rules: {
		'no-console': 'warn',
		'no-extra-parens': 'error',
		'no-template-curly-in-string': 'error',
		'require-atomic-updates': 'error',
		'accessor-pairs': 'error',
		'array-callback-return': 'error',
		'block-scoped-var': 'error',
		complexity: 'error',
		curly: 'error',
		'default-param-last': 'error',
		'dot-location': [ 'error', 'property' ],
		'dot-notation': 'error',
		eqeqeq: 'error',
		'grouped-accessor-pairs': [ 'error', 'getBeforeSet' ],
		'no-alert': 'error',
		'no-caller': 'error',
		'no-constructor-return': 'error',
		'no-div-regex': 'error',
		'no-else-return': 'error',
		'no-eq-null': 'error',
		'no-eval': 'error',
		'no-extend-native': 'error',
		'no-extra-bind': 'error',
		'no-extra-label': 'error',
		'no-floating-decimal': 'error',
		'no-implicit-coercion': 'error',
		'no-implicit-globals': 'error',
		'no-implied-eval': 'error',
		'no-invalid-this': 'error',
		'no-iterator': 'error',
		'no-labels': 'error',
		'no-lone-blocks': 'error',
		'no-loop-func': 'error',
		'no-loop-func': 'error',
		'no-multi-spaces': 'error',
		'no-multi-str': 'error',
		'no-new-func': 'error',
		'no-new-wrappers': 'error',
		'no-octal-escape': 'error',
		'no-param-reassign': 'error',
		'no-proto': 'error',
		'no-return-assign': 'error',
		'no-return-await': 'error',
		'no-script-url': 'error',
		'no-self-compare': 'error',
		'no-sequences': 'error',
		'no-throw-literal': 'error',
		'no-unmodified-loop-condition': 'error',
		'no-unused-expressions': [
			'error',
			{
				allowShortCircuit: true,
				allowTernary: true
			}
		],
		'no-useless-call': 'error',
		'no-useless-concat': 'error',
		'no-useless-return': 'error',
		'no-void': 'error',
		'no-warning-comments': 'warn',
		'prefer-named-capture-group': 'error',
		'prefer-promise-reject-errors': 'error',
		'prefer-regex-literals': 'error',
		radix: 'error',
		'require-await': 'off',
		'require-unicode-regexp': 'error',
		yoda: 'error',
		'no-label-var': 'error',
		'no-undef-init': 'error',
		'no-undefined': 'error',
		'no-unused-vars': [ 'error', { args: 'none' } ],
		'no-use-before-define': 'error',
		'callback-return': 'error',
		'global-require': 'error',
		'no-buffer-constructor': 'error',
		'no-mixed-requires': 'error',
		'no-new-require': 'error',
		'no-path-concat': 'error',
		'no-sync': 'error',
		'array-bracket-newline': [ 'error', 'consistent' ],
		'array-bracket-spacing': [ 'error', 'always' ],
		'array-element-newline': [ 'error', 'consistent' ],
		'block-spacing': 'error',
		'brace-style': 'error',
		camelcase: 'error',
		'comma-dangle': 'error',
		'comma-spacing': 'error',
		'comma-style': 'error',
		'computed-property-spacing': 'error',
		'eol-last': 'error',
		'func-call-spacing': 'error',
		'func-names': 'error',
		'func-style': 'error',
		'function-call-argument-newline': [ 'error', 'consistent' ],
		'function-paren-newline': 'error',
		'implicit-arrow-linebreak': 'error',
		indent: [ 'error', 'tab', { SwitchCase: 1 } ],
		'jsx-quotes': 'error',
		'key-spacing': 'error',
		'keyword-spacing': 'error',
		'linebreak-style': 'error',
		'lines-between-class-members': 'error',
		'multiline-comment-style': 'error',
		'multiline-ternary': [ 'error', 'always-multiline' ],
		'new-cap': 'error',
		'new-parens': [ 'error', 'never' ],
		'newline-per-chained-call': 'error',
		'no-array-constructor': 'error',
		'no-bitwise': 'error',
		'no-lonely-if': 'error',
		'no-mixed-operators': 'error',
		'no-multi-assign': 'error',
		'no-multiple-empty-lines': [
			'error',
			{
				max: 1,
				maxEOF: 1
			}
		],
		'no-nested-ternary': 'error',
		'no-new-object': 'error',
		'no-trailing-spaces': 'error',
		'no-underscore-dangle': 'error',
		'no-unneeded-ternary': 'error',
		'no-whitespace-before-property': 'error',
		'nonblock-statement-body-position': 'error',
		'object-curly-newline': 'error',
		'object-curly-spacing': [ 'error', 'always' ],
		'one-var': [ 'error', 'never' ],
		'operator-assignment': 'error',
		'operator-linebreak': 'error',
		'padded-blocks': [ 'error', 'never' ],
		'padding-line-between-statements': [ // TODO: Revisit this setting
			'error',
			{ blankLine: 'always', prev: '*', next: 'return' },
			{ blankLine: 'always', prev: [ 'const', 'let', 'var' ], next: '*' },
			{ blankLine: 'any', prev: [ 'const', 'let', 'var' ], next: [ 'const', 'let', 'var' ] },
			{ blankLine: 'always', prev: 'directive', next: '*' },
			{ blankLine: 'any', prev: 'directive', next: 'directive' }
		],
		'prefer-exponentiation-operator': 'error',
		'prefer-object-spread': 'error',
		'quote-props': [ 'error', 'as-needed' ],
		quotes: [ 'error', 'single' ],
		semi: [ 'error', 'never' ],
		'semi-spacing': 'error',
		'semi-style': 'error',
		'space-before-blocks': 'error',
		'space-before-function-paren': 'error',
		'space-in-parens': 'error',
		'space-infix-ops': 'error',
		'space-unary-ops': [
			'error',
			{
				words: true,
				nonwords: false
			}
		],
		'spaced-comment': 'error',
		'switch-colon-spacing': 'error',
		'template-tag-spacing': 'error',
		'unicode-bom': 'error',
		'arrow-body-style': [ 'error', 'as-needed' ],
		'arrow-parens': [ 'error', 'as-needed' ],
		'arrow-spacing': 'error',
		'generator-star-spacing': 'error',
		'no-confusing-arrow': 'error',
		'no-duplicate-imports': 'error',
		'no-useless-computed-key': [
			'error',
			{
				enforceForClassMembers: true
			}
		],
		'no-useless-constructor': 'error',
		'no-useless-rename': 'error',
		'no-var': 'error',
		'object-shorthand': 'error',
		'prefer-arrow-callback': 'error',
		'prefer-const': 'error',
		'prefer-destructuring': 'error',
		'prefer-destructuring': 'error',
		'prefer-numeric-literals': 'error',
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'prefer-template': 'error',
		'rest-spread-spacing': 'error',
		'symbol-description': 'error',
		'template-curly-spacing': 'error',
		'yield-star-spacing': 'error'
	}
}
